version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - corenetwork
    restart: always

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        IS_IN_PRODUCTION: ${IS_IN_PRODUCTION}
    volumes:
      - .:/app
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - corenetwork
    restart: always

volumes:
  postgres_data:

networks:
  corenetwork:
    driver: bridge